---
title: "Vetiver Research"
date: August 2022
format: 
    html: 
        toc: true
---

# Motivation

Main questions to answer: _is there anything in our vocabulary we should change?_ and _where are our shortcomings? are these things that are out of scope, or that need more investment?_

# Literature review

# Discussion

## Current standing

- Confident in version, deploy, monitor
- Importance of modularity

## Scope

- DAGs
- model registries

## Intended future investments

- monitoring, how much is infrastructure dependent?
- The language of MLOps is still developing. Many terms such as "batch processing" have multiple conflicting meanings. We proposed to create a glossary of how we use terms in vetiver's documentation. (or put this in current standing?)
- incorporation of vetiver components with other MLOps projects
- clarification of where vetiver succeed in "winning points" as per "The ML Test Score: A Rubric for ML Production Readiness and Technical Debt Reduction" 


# Final remarks

After reading, we feel confident in vetiver's scope of versioning, deploying, and monitoring models. We feel vetiver's strengths lie in its ability to quickly prototype REST APIs, and then scale these prototypes safely.

# Our reading list

Books:

- [_Designing Machine Learning Systems_](https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/) by Chip Huyen

Articles:

- [“Machine Learning Operations (MLOps): Overview, Definition, and Architecture”](https://arxiv.org/abs/2205.02302) by Kreuzberger et al
- [“From Concept Drift to Model Degradation: An Overview on Performance-Aware Drift Detectors”](https://arxiv.org/abs/2203.11070) by Bayram et al
- [“Towards Observability for Production Machine Learning Pipelines”](https://arxiv.org/pdf/2108.13557.pdf) by Shankar et al
- ["The ML Test Score: A Rubric for ML Production Readiness and Technical Debt Reduction"](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/aad9f93b86b7addfea4c419b9100c6cdd26cacea.pdf) by Breck et al

Web content:

- [_How ML Breaks: A Decade of Outages for One Large ML Pipeline_](https://www.youtube.com/watch?v=hBMHohkRgAA) by Papasian and Underwood
- [_MLOps Principles_](https://ml-ops.org/content/mlops-principles) by INNOQ
- [_Google’s Practitioners Guide to MLOps_](https://services.google.com/fh/files/misc/practitioners_guide_to_mlops_whitepaper.pdf) by Salama et al
- [_Gently Down the Stream_](https://www.gentlydownthe.stream/) by Mitch Seymour
